const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || SUHAIL_07_14_09_29_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICA5MyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTgyLFxuICAgICAgICA3MixcbiAgICAgICAgNCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMyxcbiAgICAgICAgMjIsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjU0LFxuICAgICAgICAzNSxcbiAgICAgICAgOTIsXG4gICAgICAgIDE0MSxcbiAgICAgICAgNjksXG4gICAgICAgIDIzMixcbiAgICAgICAgNjYsXG4gICAgICAgIDY2LFxuICAgICAgICAxODYsXG4gICAgICAgIDQwLFxuICAgICAgICAxMyxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMjAsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTA4LFxuICAgICAgICA2NCxcbiAgICAgICAgMTgyLFxuICAgICAgICAzMCxcbiAgICAgICAgMTM5LFxuICAgICAgICAxMDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTIsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjMwLFxuICAgICAgICAzNSxcbiAgICAgICAgMTAxLFxuICAgICAgICAyMzEsXG4gICAgICAgIDgxLFxuICAgICAgICAyOCxcbiAgICAgICAgMjEwLFxuICAgICAgICAxODIsXG4gICAgICAgIDY3LFxuICAgICAgICAyMjYsXG4gICAgICAgIDI1MixcbiAgICAgICAgNDQsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTgsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTk0LFxuICAgICAgICAxMjMsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjIyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDk3LFxuICAgICAgICAzNSxcbiAgICAgICAgMTk2LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMjIsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxNzgsXG4gICAgICAgIDI1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMjQsXG4gICAgICAgIDM3LFxuICAgICAgICAyMjIsXG4gICAgICAgIDY5LFxuICAgICAgICA1OSxcbiAgICAgICAgMTQsXG4gICAgICAgIDM0LFxuICAgICAgICAxOTEsXG4gICAgICAgIDQ5LFxuICAgICAgICAzMixcbiAgICAgICAgODEsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMTI4LFxuICAgICAgICAxMjMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTIxLFxuICAgICAgICA4MyxcbiAgICAgICAgMTMsXG4gICAgICAgIDQ4LFxuICAgICAgICAxMzcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTA2LFxuICAgICAgICAxMjksXG4gICAgICAgIDkyLFxuICAgICAgICA5NSxcbiAgICAgICAgMjA0LFxuICAgICAgICAxMTYsXG4gICAgICAgIDE4LFxuICAgICAgICA1NCxcbiAgICAgICAgMjYsXG4gICAgICAgIDIxMyxcbiAgICAgICAgNzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTM0LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE1LFxuICAgICAgICAxMTYsXG4gICAgICAgIDMyLFxuICAgICAgICAxMjYsXG4gICAgICAgIDY4LFxuICAgICAgICAyMDQsXG4gICAgICAgIDMyLFxuICAgICAgICA4NSxcbiAgICAgICAgMTg3LFxuICAgICAgICAxMzAsXG4gICAgICAgIDIyNixcbiAgICAgICAgMTUsXG4gICAgICAgIDQ0LFxuICAgICAgICAyNixcbiAgICAgICAgMTcxLFxuICAgICAgICA3MixcbiAgICAgICAgMTk5LFxuICAgICAgICAxODUsXG4gICAgICAgIDc5LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjgsXG4gICAgICAgIDUzLFxuICAgICAgICAxMzIsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMTMsXG4gICAgICAgIDg0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OCxcbiAgICAgICAgMTkxLFxuICAgICAgICAxMzQsXG4gICAgICAgIDQ5LFxuICAgICAgICAyNDMsXG4gICAgICAgIDEwNixcbiAgICAgICAgMjMyLFxuICAgICAgICAxODYsXG4gICAgICAgIDgxLFxuICAgICAgICAxMzIsXG4gICAgICAgIDI5LFxuICAgICAgICA2MSxcbiAgICAgICAgMjM2LFxuICAgICAgICAxOTEsXG4gICAgICAgIDI1NSxcbiAgICAgICAgNDAsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjEzLFxuICAgICAgICAxMTksXG4gICAgICAgIDAsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxOTksXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxNjYsXG4gICAgICAgIDEwMixcbiAgICAgICAgNDcsXG4gICAgICAgIDQ0LFxuICAgICAgICA3MixcbiAgICAgICAgMTUsXG4gICAgICAgIDEwOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDksXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMjEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTQwLFxuICAgICAgICAxNTQsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxOTMsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNTksXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjM0LFxuICAgICAgICAyNDksXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTM3LFxuICAgICAgICAxNzEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjQyLFxuICAgICAgICAyNyxcbiAgICAgICAgMjM1LFxuICAgICAgICAxOTEsXG4gICAgICAgIDg4LFxuICAgICAgICAyMjgsXG4gICAgICAgIDc4LFxuICAgICAgICAzLFxuICAgICAgICA2MixcbiAgICAgICAgMTIzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIzMixcbiAgICAgICAgICAxMixcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAyMzEsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgNzZcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMyxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICA5NixcbiAgICAgICAgICA2MSxcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAyNixcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDEwMlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjMzLFxuICAgICAgICAxODEsXG4gICAgICAgIDEyMSxcbiAgICAgICAgNDMsXG4gICAgICAgIDUwLFxuICAgICAgICAxODcsXG4gICAgICAgIDM3LFxuICAgICAgICAxMzYsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTE3LFxuICAgICAgICAyMTUsXG4gICAgICAgIDYyLFxuICAgICAgICAyNyxcbiAgICAgICAgNTQsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTAyLFxuICAgICAgICAyNDMsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNDAsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjE2LFxuICAgICAgICAxODgsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTMwLFxuICAgICAgICA0MixcbiAgICAgICAgMjUzLFxuICAgICAgICA3NSxcbiAgICAgICAgMTk1LFxuICAgICAgICA3OCxcbiAgICAgICAgMTgsXG4gICAgICAgIDY3LFxuICAgICAgICAxNjIsXG4gICAgICAgIDYzLFxuICAgICAgICA1LFxuICAgICAgICAyMzEsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjUsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTA5LFxuICAgICAgICAxMTksXG4gICAgICAgIDExNCxcbiAgICAgICAgMjQsXG4gICAgICAgIDMsXG4gICAgICAgIDQwLFxuICAgICAgICAyNTMsXG4gICAgICAgIDM1LFxuICAgICAgICA2OSxcbiAgICAgICAgMjM1LFxuICAgICAgICAyMDIsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjExLFxuICAgICAgICAxODQsXG4gICAgICAgIDExMyxcbiAgICAgICAgOTMsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTA5LFxuICAgICAgICAyNTQsXG4gICAgICAgIDU1LFxuICAgICAgICAxMzAsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTAzLFxuICAgICAgICAwXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAzNyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIwdjJvOXBVSHh2dmh5OEwrcFVBYzg2ckVGUWtEM3hXMmgzVjMvaStQWXdjPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIzNDgwMzQ4MTQ4MzZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkUyRUMyRkQxNjQ5RDI5MkQxNTIxQjA1MkM5QjFBOTFGXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNzU5NDA2OVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJoLTdMU0hGMFJmR0w4aW1rT01yeGlnXCIsXG4gIFwicGhvbmVJZFwiOiBcIjA3ZjU2NjMxLWU2YzYtNGUzNS05NDQ4LWVkYzAwOGQ2YzBhYVwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMTQsXG4gICAgICAxODgsXG4gICAgICAyMDgsXG4gICAgICAyMzMsXG4gICAgICAxMzcsXG4gICAgICA1MyxcbiAgICAgIDM2LFxuICAgICAgMjE1LFxuICAgICAgMjA3LFxuICAgICAgMjA2LFxuICAgICAgMTg5LFxuICAgICAgNzIsXG4gICAgICAyNTQsXG4gICAgICA1OSxcbiAgICAgIDE2MCxcbiAgICAgIDMzLFxuICAgICAgMTEyLFxuICAgICAgNzUsXG4gICAgICAxNjksXG4gICAgICAxNTdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgOTksXG4gICAgICAyMDYsXG4gICAgICAzNCxcbiAgICAgIDE4NyxcbiAgICAgIDIzNCxcbiAgICAgIDI0NSxcbiAgICAgIDI0NCxcbiAgICAgIDE3MyxcbiAgICAgIDE1MSxcbiAgICAgIDIxNSxcbiAgICAgIDE2NSxcbiAgICAgIDI1MyxcbiAgICAgIDEwNyxcbiAgICAgIDE5NSxcbiAgICAgIDg3LFxuICAgICAgNzYsXG4gICAgICAyMDUsXG4gICAgICAyMzksXG4gICAgICAxMDMsXG4gICAgICA3OFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJITkY3NDE5UlwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0ODAzNDgxNDgzNjoxMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIk91bSBBbGJhbnlcIixcbiAgICBcImxpZFwiOiBcIjcwODY3NDYzOTQ3Mjg6MTFAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTkNpa09NR0VNdjg0N2NHR0FJZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJhYlJ6TUZSMWxmU09WQk5nUmsvdzZnK1I1ank5eUx1WXdndTdKaHNJRUZVPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInpWYU5rakJLKy85bUd1bDZQd2U3WCt6R0VWWmNlazdMdWhwdWhMTmpTbGZGL0EveXMzMFl1THNmMWlpR1VraldNVHVQQjN1VVFMQlNkNVBldGxpREJnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInpPaGR6ZzFtREsvdVdkMVBBZDRPRTVETFBtZi9MaGowdGFhRjZUNGNob1pSbkhtZW10ZTRkVmhNcHVGOGczYmsrOVFJL3dOQndibWk5dmtENS9nV0F3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDgwMzQ4MTQ4MzY6MTFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDI0NCxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDgsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgODVcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyNzU5NDA2NCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQU85blwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTzluLmpzb24iOiAie1wia2V5RGF0YVwiOlwiNGNMbXExTWxyWWt6eTNROGNBLzByMTgvQnE4WGE4K2ZxcUVKQ3cwU2ZxVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxODE4NDk3MzU5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
